apiVersion: v2
name: universe-test
description: Prometheus-Grafana-BlackBoxProbing-sh.infinityfree.io

type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: prometheus
    version: "29.33.1"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: grafana
    version: "10.5.15"
    repository: "https://grafana.github.io/helm-charts"
  - name: prometheus-blackbox-exporter
    version: "11.19.1"
    repository: "https://prometheus-community.github.io/helm-charts"
